import React, { useEffect, useRef, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Crown, ArrowLeft, Compass, TrendingUp, Sparkles } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useAuth } from '../contexts/AuthContext';
import { astroAPI } from '../services/api';

const jupiterData = {
  Aries: {
    description: "The Bold Opportunist", fortune: "Pioneering", wisdom: "Instinctual", faith: "Self-Reliant",
    essence: "Jupiter in Aries expands through raw, unfiltered courage. Your luck is not a passive event but a dynamic spark generated by your ability to take the terrifying first step. Abundance flows into your life when you stop overthinking and start initiating. You find the Divine in the adrenaline of a new beginning, acting as a spiritual pioneer who clears the path for others by simply refusing to stay still.",
    beliefs: "Your moral compass is calibrated by radical authenticity and personal truth. You believe that the universe is an arena designed to reward the brave. Growth, for you, is found in the heat of action; you have little patience for armchair philosophy, preferring the wisdom gained through scars and victories.",
    luck: "Fortune favors you when you act with total decisiveness. Your 'Luck Frequency' is activated when you embrace your role as a leader. Opportunities often appear as sudden openings in the market or social circles that only stay open for those quick enough to jump through them."
  },
  Taurus: {
    description: "The Provider of Plenty", fortune: "Tangible", wisdom: "Grounded", faith: "Steady",
    essence: "Jupiter in Taurus seeks expansion through the physical senses and the material world. Your abundance is literal—reflected in wealth, comfort, and a deep, cellular connection to the beauty of nature. You grow by cultivating stability and honoring the sacredness of the Earth. You are a steward of resources, finding that the more you respect the physical plane, the more it provides for you in return.",
    beliefs: "You find meaning in the tangible and the lasting. Your philosophy is built on 'Practical Spirituality'—the belief that spiritual growth is directly reflected in how we treat our bodies, our bank accounts, and our environment. To you, a well-tended garden is as holy as a cathedral.",
    luck: "Abundance flows toward you when you practice the art of slow-cooked patience and deep gratitude. Your luck is like a giant oak tree: it takes time to establish its roots, but once it does, its growth is massive, enduring, and provides shade for everyone in your orbit."
  },
  Gemini: {
    description: "The Eternal Student", fortune: "Intellectual", wisdom: "Versatile", faith: "Curious",
    essence: "Jupiter in Gemini expands through the curiosity of the mind and the power of the network. Your luck is found in the exchange of ideas, the unexpected phone call, and your ability to see the divine symmetry in the smallest details. You grow by remaining a perpetual amateur—always learning, always questioning, and always connecting two seemingly unrelated dots to create a new map of reality.",
    beliefs: "You believe that Truth is a kaleidoscope, never fixed and always shifting. Your moral compass is guided by the realization that information is the ultimate spiritual currency. You find meaning in communication, believing that a well-placed word can change the trajectory of a life or a nation.",
    luck: "Your 'Gift of Luck' manifests as the right information appearing at exactly the perfect time. Abundance is found in your social agility; you are often 'at the right table' or 'on the right thread' purely because you followed a trail of intellectual curiosity."
  },
  Cancer: {
    description: "The Soulful Nurturer", fortune: "Emotional", wisdom: "Ancestral", faith: "Protective",
    essence: "Jupiter is exalted in Cancer, operating at its most profound spiritual capacity. You expand through emotional depth and the sacred power of the 'Home.' Your abundance is found in the richness of your inner life and the strength of your chosen tribe. You grow by widening your definition of family until it encompasses the world, acting as a cosmic parent to those who have lost their way.",
    beliefs: "You believe that kindness is the highest form of intelligence. Your philosophy is rooted in heritage, intuition, and the sanctity of the domestic sphere. You find meaning in the cycles of the moon and the tides of human emotion, believing that if the heart is cared for, the external world will take care of itself.",
    luck: "Luck flows to you when you listen to your gut and honor your vulnerability. You are protected by an unseen 'ancestral' force; when you nurture others, the universe conspires to nurture you, often providing emotional or financial windfalls from unexpected 'home' sources."
  },
  Leo: {
    description: "The Radiant Creator", fortune: "Glorious", wisdom: "Heart-Centered", faith: "Dazzling",
    essence: "Jupiter in Leo expands through the warmth of the heart and the fire of creative expression. Your abundance is expressed through art, romance, and the sheer, infectious joy of being alive. You grow by allowing your inner light to shine without apology or ego, becoming a sun that others can warm themselves by. To you, life is not a struggle to be won, but a masterpiece to be painted.",
    beliefs: "You believe in the divinity of the individual creative spark. Your philosophy is one of 'Noble Optimism,' operating on the belief that the world is a stage specifically designed for your growth and the celebration of beauty. You find meaning in praise—not for the ego, but as a confirmation that your light is reaching its mark.",
    luck: "Abundance follows your generosity. When you give from a place of abundance—whether it’s money, time, or encouragement—the universe reflects that radiance back to you. Your luck is often 'performative,' appearing when you are at your most visible and expressive."
  },
  Virgo: {
    description: "The Sacred Analyst", fortune: "Practical", wisdom: "Discerning", faith: "Diligent",
    essence: "Jupiter in Virgo finds expansion in the mastery of craft and the purification of the self. Your abundance is found in the 'Micro-Sacred'—the health of the body, the service of the hands, and the perfect execution of a necessary task. You grow through the refinement of your environment and your skills, finding that true wisdom is the ability to tell the wheat from the chaff.",
    beliefs: "Your moral compass is set to integrity and functional service. You find meaning in the idea that 'God is in the details' and that a life of service is the most direct path to the Divine. You believe that spiritual expansion is a technical process of cleaning the lens until the light can pass through clearly.",
    luck: "Fortune finds you when you are organized, humble, and helpful. Your luck isn't a random gamble; it's the inevitable, compound interest of your technical excellence and your dedication to doing things correctly. You 'stumble' upon opportunities because you were the only one disciplined enough to be in the room."
  },
  Libra: {
    description: "The Harmonizer", fortune: "Relational", wisdom: "Diplomatic", faith: "Aesthetic",
    essence: "Jupiter in Libra expands through the mirror of the 'Other.' Your abundance is found in the elegance of partnership, the beauty of symmetry, and the tireless pursuit of social justice. You grow by seeing the divine in every face you meet, acting as the diplomat who finds the middle ground where others only see conflict. You find that your world expands in direct proportion to the quality of your relationships.",
    beliefs: "You believe that Balance is the ultimate laws of the universe. Your philosophy is built on the pillars of fairness, aesthetic grace, and the spiritual contract of human connection. You find meaning in the 'We,' believing that no one reaches the mountaintop alone and that true growth is a collaborative art form.",
    luck: "Your 'Gift of Luck' almost always comes through other people. Opportunities manifest as chance meetings at galleries, soulmate connections, or legal breakthroughs. Abundance flows when you prioritize 'Win-Win' scenarios over personal gain."
  },
  Scorpio: {
    description: "The Alchemist", fortune: "Transformative", wisdom: "Penetrating", faith: "Mystical",
    essence: "Jupiter in Scorpio expands through the shadow and the mastery of the unseen. Your abundance is found in deep mysteries—psychology, occult power, shared resources, and the intensity of true intimacy. You grow by facing what others fear to look at, acting as a spiritual detective who finds the treasure buried in the darkest basements of the human experience.",
    beliefs: "You believe that Truth is never found on the surface. Your moral compass is tuned to the frequency of transformation; you grow through the cycle of death and rebirth, believing that every ending is simply a larger beginning in disguise. You find meaning in power—not to dominate, but to heal and transmute.",
    luck: "Luck arrives during your most intense crises. You have a strange, 'Vampiric' ability to find gold in the dark and to turn a total psychological or financial loss into a massive windfall. Abundance comes when you commit fully to the process of evolution."
  },
  Sagittarius: {
    description: "The Cosmic Voyager", fortune: "Expansive", wisdom: "Philosophical", faith: "Limitless",
    essence: "Jupiter is at home in Sagittarius, its power amplified to its highest frequency. You grow through literal and metaphorical travel—the crossing of borders and the breaking of mental cages. Your abundance is Freedom. You find the Divine in the far-reaching horizon, the ancient text, and the spontaneous adventure. You are a bridge between the mundane and the infinite.",
    beliefs: "You believe the universe is a friendly, intelligent place designed for your exploration. Your philosophy is expansive, unapologetically optimistic, and entirely focused on the 'Big Picture.' You believe that faith is not a feeling, but a movement toward the unknown.",
    luck: "You are the 'Luckiest Sign' in the zodiac. Fortune follows your enthusiasm like a shadow. As long as you keep moving, keep learning, and keep your gaze on the horizon, the universe provides a seemingly bottomless supply of resources, guides, and open doors."
  },
  Capricorn: {
    description: "The Ethical Architect", fortune: "Structural", wisdom: "Authoritative", faith: "Responsible",
    essence: "Jupiter in Capricorn expands through the mastery of time, discipline, and physical law. Your abundance is your legacy—the reputation you build and the structures you leave behind. You grow by treating your life like a mountain to be climbed, finding that the higher you go, the more the universe trusts you with its secrets. You are the sage who finds God in the stones and the structures.",
    beliefs: "You believe that growth must be earned to be kept. Your philosophy is one of 'Spiritual Pragmatism,' finding meaning in hard work, tradition, and the wisdom of the ancestors. You believe that the most expansive thing a person can do is take on responsibility for their community.",
    luck: "Your luck is cumulative and heavy. It grows slowly as you prove your reliability to the universe. Fortune favors you when you take the 'Hard Way' and lead with ethical vision. You are often rewarded with late-blooming success that outlasts everyone else's."
  },
  Aquarius: {
    description: "The Global Visionary", fortune: "Electric", wisdom: "Progressive", faith: "Humanitarian",
    essence: "Jupiter in Aquarius expands through the power of the collective and the vibration of the future. Your abundance is found in the network, the revolution, and the 'Aha!' moment. You grow by breaking the mold and advocating for the advancement of all humanity, acting as a spiritual lightning rod for ideas that are decades ahead of their time.",
    beliefs: "You believe in the power of the Group and the absolute freedom of the Individual. Your moral compass is set to 'Universal Truth' rather than local tradition. You find meaning in the 'Glitch'—the moment where the system breaks to allow a new, better world to be born.",
    luck: "Luck comes through your unique, often 'weird' ideas and your diverse community. Opportunities manifest as sudden 'flashes of genius' or breakthroughs within your digital or social circles. You are luckiest when you are being your most unconventional self."
  },
  Pisces: {
    description: "The Empathic Mystic", fortune: "Infinite", wisdom: "Universal", faith: "Compassionate",
    essence: "Jupiter is the ancient ruler of Pisces, granting you a limitless, oceanic abundance. You expand through surrender, art, and the dissolution of the ego. Your wealth is spiritual—an infinite connection to the Oneness of all life. You grow not by climbing, but by letting go of the shore and allowing the current of the Divine to take you where it will.",
    beliefs: "You believe that boundaries are illusions and that separation is a lie. Your philosophy is one of unconditional compassion and the realization that the universe is a dream we are all dreaming together. You find meaning in silence, music, and the spaces between the words.",
    luck: "Your luck is pure synchronicity. When you flow with life rather than fighting it, the universe provides exactly what you need through 'miraculous' coincidences. Abundance arrives when you stop chasing it and simply make yourself available to receive it."
  }
};

const Jupiter = () => {
  const { signName } = useParams();
  const canvasRef = useRef(null);
  const { user } = useAuth();

  const normalizeSign = (name) => {
    if (!name) return 'Sagittarius';
    const formatted = name.charAt(0).toUpperCase() + name.slice(1).toLowerCase();
    return jupiterData[formatted] ? formatted : 'Sagittarius';
  };

  const [jupSign, setJupSign] = useState(normalizeSign(signName));
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchJupiterSign = async () => {
      if (signName) {
        setJupSign(normalizeSign(signName));
        setLoading(false);
        return;
      }
      if (!user?.birth?.date) {
        setLoading(false);
        return;
      }
      try {
        setLoading(true);
        const response = await astroAPI.getNatal({
          date: user.birth.date,
          month: user.birth.month,
          year: user.birth.year,
          hour: user.birth.hour || 0,
          minute: user.birth.minute || 0,
          latitude: user.birth.latitude || 0,
          longitude: user.birth.longitude || 0,
          timezone: user.birth.timezone || 0
        });
        const planetaryData = response.data?.data?.planets;
        const planetInfo = planetaryData?.find(p => p.name === 'Jupiter');
        if (planetInfo?.sign) setJupSign(normalizeSign(planetInfo.sign));
      } catch (err) {
        console.error('Failed to fetch Jupiter sign:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchJupiterSign();
  }, [user, signName]);

  // Gold Dust / Spore Animation
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    let particles = [];
    let animationFrameId;

    const resize = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
      initParticles();
    };

    class Particle {
      constructor() { this.reset(); }
      reset() {
        this.x = Math.random() * canvas.width;
        this.y = Math.random() * canvas.height;
        this.size = Math.random() * 1.5 + 0.5;
        this.speedX = (Math.random() - 0.5) * 0.3;
        this.speedY = (Math.random() - 0.5) * 0.3;
        this.opacity = Math.random() * 0.5;
        this.pulse = Math.random() * 0.02;
      }
      draw() {
        ctx.fillStyle = `rgba(217, 119, 6, ${this.opacity})`;
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
        ctx.fill();
      }
      update() {
        this.x += this.speedX;
        this.y += this.speedY;
        this.opacity += this.pulse;
        if (this.opacity > 0.6 || this.opacity < 0.1) this.pulse *= -1;
        if (this.x < 0 || this.x > canvas.width) this.speedX *= -1;
        if (this.y < 0 || this.y > canvas.height) this.speedY *= -1;
      }
    }

    const initParticles = () => {
      particles = [];
      const count = (canvas.width * canvas.height) / 15000;
      for (let i = 0; i < count; i++) particles.push(new Particle());
    };

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      particles.forEach((p) => { p.update(); p.draw(); });
      animationFrameId = requestAnimationFrame(animate);
    };

    window.addEventListener('resize', resize);
    resize(); animate();
    return () => {
      window.removeEventListener('resize', resize);
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  const currentData = jupiterData[jupSign];

  return (
    <div className="bg-[#050505] min-h-screen text-white overflow-x-hidden selection:bg-amber-900/30">
      <canvas ref={canvasRef} className="fixed inset-0 z-0 pointer-events-none" />
      <Navbar />
      <main className="relative z-10 max-w-5xl mx-auto pt-32 px-5 pb-20">
        <Link to="/natal" className="inline-flex items-center gap-2 text-amber-700 hover:text-white transition-colors mb-10 group">
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
          Back to Natal Architecture
        </Link>

        <section className="flex flex-col md:flex-row items-center gap-10 mb-16 text-center md:text-left">
          <div className="text-8xl md:text-9xl leading-none bg-linear-to-br from-orange-800 via-amber-900 to-[#3d2b1f] bg-clip-text text-transparent filter drop-shadow-[0_0_20px_rgba(120,53,15,0.4)]">
            ♃
          </div>
          <div className="flex-1">
            <h1 className="text-5xl md:text-7xl font-bold uppercase tracking-widest mb-2">
               {loading ? 'Loading...' : `Jupiter in ${jupSign}`}
            </h1>
            <p className="text-amber-700/60 italic text-lg mb-6">
               {loading ? 'Calculating...' : `The Benefic: ${currentData.description}`}
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <MetaItem label="Fortune" value={currentData.fortune} color="text-amber-600" />
              <MetaItem label="Wisdom" value={currentData.wisdom} color="text-amber-600" />
              <MetaItem label="Faith" value={currentData.faith} color="text-amber-600" />
            </div>
          </div>
        </section>

        {!loading && (
          <>
            <div className="bg-white/5 backdrop-blur-xl border border-amber-900/30 rounded-[30px] p-8 md:p-12 mb-8 shadow-2xl">
              <h2 className="text-3xl font-semibold text-amber-200 mb-4 flex items-center gap-3">
                  <TrendingUp className="text-amber-600" /> The Path of Expansion
              </h2>
              <p className="text-lg leading-relaxed text-slate-300 font-light">
                {currentData.essence}
              </p>
            </div>

            <div className="bg-white/5 backdrop-blur-xl border border-white/5 rounded-[30px] p-8 md:p-12 space-y-12 shadow-2xl">
              <ContentSection Icon={Compass} title="Guiding Beliefs" text={currentData.beliefs} color="text-amber-700" />
              <ContentSection Icon={Sparkles} title="Gift of Luck" text={currentData.luck} color="text-amber-500" />
            </div>
          </>
        )}
      </main>
      <Footer />
    </div>
  );
};

const MetaItem = ({ label, value, color }) => (
  <div className="bg-white/5 border border-white/10 rounded-xl px-5 py-3 text-center">
    <span className={`block text-[10px] uppercase tracking-widest ${color} font-bold mb-1`}>{label}</span>
    <span className="text-base font-semibold">{value}</span>
  </div>
);

const ContentSection = ({ Icon, title, text, color }) => (
  <div className="grid grid-cols-1 md:grid-cols-[80px_1fr] gap-6 group">
    <div className={`mx-auto md:mx-0 w-16 h-16 rounded-full bg-amber-900/10 border border-amber-900 flex items-center justify-center ${color} shadow-lg`}>
      <Icon size={28} />
    </div>
    <div className="text-center md:text-left">
      <h2 className="text-2xl font-semibold mb-3">{title}</h2>
      <p className="text-white/70 leading-relaxed font-light">{text}</p>
    </div>
  </div>
);

export default Jupiter;